### ISSUE TITLE
Photo Property not importing properly

### ISSUE THREAD

**Issue by sharpsaravanan** [frknkrc44/vcf_dart#1]
Photo property returns only first line.
only "https://lh3.googleusercontent.com/contacts/AG6tpzFfv2vRgrTeT1BTaF5v-j"
it should be "https://lh3.googleusercontent.com/contacts/AG6tpzFfv2vRgrTeT1BTaF5v-jUSXTHkD4evejsZjjR5rATQjI0VPUzo"
( VCard exported from google account as vCard (for Android or iOS contacts))

sample VCard

BEGIN:VCARD
VERSION:3.0
N:;Ram;;;
TEL;TYPE=CELL:+911231231234
PHOTO:https://lh3.googleusercontent.com/contacts/AG6tpzFfv2vRgrTeT1BTaF5v-j
 USXTHkD4evejsZjjR5rATQjI0VPUzo
CATEGORIES:myContacts
END:VCARD

**Comment by frknkrc44** [comment]
Thank you for your report. I tried to fix it and seems working. Can you try with the latest version? @sharpsaravanan
